variables: # variable that will be avialbe for the entire pipleine and mainly needed in both deploy env.
  NETLIFY_SITE_ID: 'e811a441-a530-4211-bdc9-374bf821253e' 
    
stages: #keep in your mind that Gitlab defines a  default stages such as build, test, and deploy so if you didn't idenitfy them they are already there.
  - build
  - test
  - deploy

build-website:
  image: node:22-alpine
  stage: build
  script:
    - echo "check node and npm versions"
    - ls -la
    - node --version
    - npm --version
    - npm ci
    - ls -la
    - npm run build
  artifacts:
    paths:
      - build/

test-website:
  image: alpine
  stage: test
  script:
    - echo "Start Testing"
    - test -f build/index.html

netlify-deploy-prod:
  image: node:22-alpine
  stage: deploy
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  when: manual
  before_script: # use the before script to install the tools that you are going to use in the script of the specified job. 
    - npm install netlify-cli -g
    - apk add curl
  script:
    - netlify --version
    - netlify status
    - echo "Deploying to site id:${NETLIFY_SITE_ID}"
    - netlify deploy --prod --dir build #this to mention get the build version of our website from the build dir in the artifacts and this is prod env.
