image: node:18

cache:
  paths:
    - node_modules/

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/translation-app/
    expire_in: 1 week

deploy:
  stage: deploy
  image: node:18
  script:
    - npm install -g netlify-cli
    - netlify deploy --dir=dist/translation-app --prod
  only:
    - main
  environment:
    name: production
    url: https://translation-app.netlify.app 