variables:
  NETLIFY_SITE_ID: 'e811a441-a530-4211-bdc9-374bf821253e'
  NETLIFY_AUTH_TOKEN: 'nfp_LmtT1TGyEqDh2AWKv9eDTRL26Jcu3wbpa4f7'
    
stages:
  - build
  - deploy

build:
  image: node:22-alpine
  stage: build
  script:
    - echo "Installing dependencies..."
    - npm install --legacy-peer-deps
    - echo "Building application..."
    - npm run build
    - echo "Verifying build output..."
    - ls -la dist/
    - test -d dist/translation-app
    - test -f dist/translation-app/browser/index.html
    - test -f dist/translation-app/browser/main*.js
    - test -f dist/translation-app/browser/styles*.css
  artifacts:
    paths:
      - dist/
    expire_in: 1 week
    when: on_success

deploy:
  image: node:22-alpine
  stage: deploy
  needs: ["build"]
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  before_script:
    - npm install netlify-cli -g
  script:
    - echo "Deploying to Netlify..."
    - netlify deploy --prod --dir dist/translation-app/browser --auth $NETLIFY_AUTH_TOKEN --site $NETLIFY_SITE_ID
