variables:
  NETLIFY_SITE_ID: 'e811a441-a530-4211-bdc9-374bf821253e'
    
stages:
  - build
  - test
  - deploy

build-website:
  image: node:22-alpine
  stage: build
  script:
    - echo "Installing dependencies..."
    - npm install --legacy-peer-deps
    - echo "Building application..."
    - npm run build
    - echo "Verifying build output..."
    - ls -la dist/
  artifacts:
    paths:
      - dist/
    expire_in: 1 week
    when: on_success
    reports:
      dotenv: build.env

test-website:
  image: node:22-alpine
  stage: test
  needs: ["build-website"]
  script:
    - echo "Testing build artifacts..."
    - ls -la dist/
    - test -d dist/translation-app
    - echo "Testing completed successfully"
  artifacts:
    paths:
      - dist/
    expire_in: 1 week
    when: on_success

netlify-deploy-prod:
  image: node:22-alpine
  stage: deploy
  needs:
    - build-website
    - test-website
  dependencies:
    - build-website
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  when: manual
  before_script:
    - npm install netlify-cli -g
    - apk add curl
  script:
    - netlify --version
    - netlify status
    - echo "Deploying to site id:${NETLIFY_SITE_ID}"
    - ls -la dist/translation-app/
    - netlify deploy --prod --dir dist/translation-app
