variables:
  NETLIFY_SITE_ID: 'e811a441-a530-4211-bdc9-374bf821253e'
    
stages:
  - build
  - test
  - deploy

build-website:
  image: node:22-alpine
  stage: build
  script:
    - echo "check node and npm versions"
    - ls -la
    - node --version
    - npm --version
    - npm install --legacy-peer-deps
    - ls -la
    - npm run build
  artifacts:
    paths:
      - dist/translation-app/

test-website:
  image: alpine
  stage: test
  script:
    - echo "Start Testing"
    - test -f dist/translation-app/index.html

netlify-deploy-prod:
  image: node:22-alpine
  stage: deploy
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  when: manual
  before_script:
    - npm install netlify-cli -g
    - apk add curl
  script:
    - netlify --version
    - netlify status
    - echo "Deploying to site id:${NETLIFY_SITE_ID}"
    - netlify deploy --prod --dir dist/translation-app 