image: node:20

cache:
  paths:
    - node_modules/

stages:
  - build
  - deploy

variables:
  DEEPL_API_KEY: $DEEPL_API_KEY  # This will be set in GitLab CI/CD variables
  NETLIFY_SITE_ID: $NETLIFY_SITE_ID  # This will be set in GitLab CI/CD variables
  NETLIFY_AUTH_TOKEN: $NETLIFY_AUTH_TOKEN  # This will be set in GitLab CI/CD variables

build:
  stage: build
  script:
    - npm install
    - npm run build:prod
  artifacts:
    paths:
      - dist/translation-app/
    expire_in: 1 week

pages:
  stage: deploy
  script:
    - cp -r dist/translation-app/* public/
  artifacts:
    paths:
      - public
  only:
    - main  # or your default branch name

deploy:
  image: node:22-alpine
  stage: deploy
  needs: ["build"]
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  before_script:
    - npm install netlify-cli -g
  script:
    - echo "Deploying to Netlify..."
    - netlify deploy --prod --dir dist/translation-app/browser --auth $NETLIFY_AUTH_TOKEN --site $NETLIFY_SITE_ID
