image: node:22-alpine

cache:
  paths:
    - node_modules/

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm install --legacy-peer-deps
    - npm run build
  artifacts:
    paths:
      - dist/translation-app/
    expire_in: 1 week

deploy:
  image: node:22-alpine
  stage: deploy
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  before_script:
    - npm install netlify-cli -g
    - apk add curl
  script:
    - netlify --version
    - netlify status
    - echo "Deploying to site id:${NETLIFY_SITE_ID}"
    - netlify deploy --prod --dir dist/translation-app
    - echo "Waiting for deployment to be available..."
    - sleep 30
    - curl -s "https://translation-app-test.netlify.app/" | grep -q "app-root" || (echo "Smoke test failed" && exit 1) 