image: node:22-alpine

cache:
  paths:
    - node_modules/

stages:
  - build
  - deploy_staging
  - deploy-prod

build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/translation-app/
    expire_in: 1 week

netlify-deploy-staging:
  image: node:22-alpine
  stage: deploy_staging
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  before_script:
    - npm install netlify-cli -g
    - apk add curl
  script:
    - netlify --version
    - netlify status
    - echo "Deploying to site id:${NETLIFY_SITE_ID}"
    - netlify deploy --alias staging --dir dist/translation-app
    - curl 'https://translation-app.netlify.app/' | grep 'app-root'

netlify-deploy-prod:
  image: node:22-alpine
  stage: deploy-prod
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  when: manual
  before_script:
    - npm install netlify-cli -g
    - apk add curl
  script:
    - netlify --version
    - netlify status
    - echo "Deploying to site id:${NETLIFY_SITE_ID}"
    - netlify deploy --prod --dir dist/translation-app
    - curl 'https://translation-app.netlify.app/' | grep 'app-root' 