image: node:20

cache:
  paths:
    - node_modules/

stages:
  - build
  - deploy

variables:
  DEEPL_API_KEY: $DEEPL_API_KEY  # This will be set in GitLab CI/CD variables
  NETLIFY_SITE_ID: $NETLIFY_SITE_ID  # This will be set in GitLab CI/CD variables
  NETLIFY_AUTH_TOKEN: $NETLIFY_AUTH_TOKEN  # This will be set in GitLab CI/CD variables

build:
  stage: build
  script:
    - npm install --legacy-peer-deps
    - npm run build:prod
  artifacts:
    paths:
      - dist/translation-app/
      - netlify/
    expire_in: 1 week

deploy:
  image: node:20
  stage: deploy
  needs: ["build"]
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  before_script:
    - npm install -g netlify-cli
  script:
    - echo "Deploying to Netlify..."
    - netlify deploy --prod --dir dist/translation-app/browser --auth $NETLIFY_AUTH_TOKEN --site $NETLIFY_SITE_ID
    - echo "Setting environment variables..."
    - netlify env:set DEEPL_API_KEY $DEEPL_API_KEY --auth $NETLIFY_AUTH_TOKEN --site $NETLIFY_SITE_ID
